name: "MP5"
files:
  - compile:
    - "ConnectN.java"
    - "Player.java"
    test: ConnectN
secure: config/security/security.policy
reporting:
  default: post
  post: "https://cs125.cs.illinois.edu/grades"
  directory: ""
notes:
  "Note that the maximum local grade is 90/100. 10 points will be provided
  during official grading if you have committed code that earns at least 50
  points by Friday 10/27/2017 at 5PM."
checkstyle:
  name: "checkstyle Tests"
  missing:
    score: 0
    message: "checkstyle failed to run"
    name: "checkstyle"
  selectors:
    - selector: "count(//file/error) = 0"
      score: 10
      message: "No checkstyle errors were reported"
      name: "checkstyle"
    - selector: "count(//file/error) > 0"
      score: 0
      message: "checkstyle errors were reported"
      name: "checkstyle"
test:
  name: "testNG Tests"
  selectors:
    - selector: "count(//testcase[@name='testTitle']) = 1 and count(//testcase[@name='testTitle']//failure) > 0"
      score: 0
      message: "testTitle failed"
      name: "testTitle"
    - selector: "count(//testcase[@name='testTitle']) = 1 and count(//testcase[@name='testTitle']//failure) = 0"
      score: 5
      message: "testTitle succeeded"
      name: "testTitle"
    - selector: "count(//testcase[@name='testGetAndSetWidth']) = 1 and count(//testcase[@name='testGetAndSetWidth']//failure) > 0"
      score: 0
      message: "testGetAndSetWidth failed"
      name: "testGetAndSetWidth"
    - selector: "count(//testcase[@name='testGetAndSetWidth']) = 1 and count(//testcase[@name='testGetAndSetWidth']//failure) = 0"
      score: 5
      message: "testGetAndSetWidth succeeded"
      name: "testGetAndSetWidth"
    - selector: "count(//testcase[@name='testGetAndSetHeight']) = 1 and count(//testcase[@name='testGetAndSetHeight']//failure) > 0"
      score: 0
      message: "testGetAndSetHeight failed"
      name: "testGetAndSetHeight"
    - selector: "count(//testcase[@name='testGetAndSetHeight']) = 1 and count(//testcase[@name='testGetAndSetHeight']//failure) = 0"
      score: 5
      message: "testGetAndSetHeight succeeded"
      name: "testGetAndSetHeight"
    - selector: "count(//testcase[@name='testGetAndSetN']) = 1 and count(//testcase[@name='testGetAndSetN']//failure) > 0"
      score: 0
      message: "testGetAndSetN failed"
      name: "testGetAndSetN"
    - selector: "count(//testcase[@name='testGetAndSetN']) = 1 and count(//testcase[@name='testGetAndSetN']//failure) = 0"
      score: 5
      message: "testGetAndSetN succeeded"
      name: "testGetAndSetN"
    - selector: "count(//testcase[@name='testConstructors']) = 1 and count(//testcase[@name='testConstructors']//failure) > 0"
      score: 0
      message: "testConstructors failed"
      name: "testConstructors"
    - selector: "count(//testcase[@name='testConstructors']) = 1 and count(//testcase[@name='testConstructors']//failure) = 0"
      score: 10
      message: "testConstructors succeeded"
      name: "testConstructors"
    - selector: "count(//testcase[@name='testGetAndSetBoard']) = 1 and count(//testcase[@name='testGetAndSetBoard']//failure) > 0"
      score: 0
      message: "testGetAndSetBoard failed"
      name: "testGetAndSetBoard"
    - selector: "count(//testcase[@name='testGetAndSetBoard']) = 1 and count(//testcase[@name='testGetAndSetBoard']//failure) = 0"
      score: 15
      message: "testGetAndSetBoard succeeded"
      name: "testGetAndSetBoard"
    - selector: "count(//testcase[@name='testWinner']) = 1 and count(//testcase[@name='testWinner']//failure) > 0"
      score: 0
      message: "testWinner failed"
      name: "testWinner"
    - selector: "count(//testcase[@name='testWinner']) = 1 and count(//testcase[@name='testWinner']//failure) = 0"
      score: 10
      message: "testWinner succeeded"
      name: "testWinner"
    - selector: "count(//testcase[@name='testEquals']) = 1 and count(//testcase[@name='testEquals']//failure) > 0"
      score: 0
      message: "testEquals failed"
      name: "testEquals"
    - selector: "count(//testcase[@name='testEquals']) = 1 and count(//testcase[@name='testEquals']//failure) = 0"
      score: 10
      message: "testEquals succeeded"
      name: "testEquals"
    - selector: "count(//testcase[@name='testStaticMethods']) = 1 and count(//testcase[@name='testStaticMethods']//failure) > 0"
      score: 0
      message: "testStaticMethods failed"
      name: "testStaticMethods"
    - selector: "count(//testcase[@name='testStaticMethods']) = 1 and count(//testcase[@name='testStaticMethods']//failure) = 0"
      score: 10
      message: "testStaticMethods succeeded"
      name: "testStaticMethods"
    - selector: "count(//testcase[@name='testGameCount']) = 1 and count(//testcase[@name='testGameCount']//failure) > 0"
      score: 0
      message: "testGameCount failed"
      name: "testGameCount"
    - selector: "count(//testcase[@name='testGameCount']) = 1 and count(//testcase[@name='testGameCount']//failure) = 0"
      score: 5
      message: "testGameCount succeeded"
      name: "testGameCount"

# vim: ts=2:sw=2:et
